/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FishProfile = IDL.Record({
  'id' : IDL.Nat,
  'incompatibleWith' : IDL.Vec(IDL.Text),
  'maxPH' : IDL.Float64,
  'minPH' : IDL.Float64,
  'plants' : IDL.Vec(IDL.Text),
  'minTemp' : IDL.Nat,
  'diet' : IDL.Text,
  'name' : IDL.Text,
  'compatibleWith' : IDL.Vec(IDL.Text),
  'habitat' : IDL.Text,
  'lighting' : IDL.Text,
  'scientificName' : IDL.Text,
  'minTankSize' : IDL.Nat,
  'maxTemp' : IDL.Nat,
  'filtration' : IDL.Text,
  'substrate' : IDL.Text,
  'maxTankSize' : IDL.Nat,
  'decorations' : IDL.Vec(IDL.Text),
});
export const WaterLog = IDL.Record({
  'id' : IDL.Nat,
  'ph' : IDL.Float64,
  'temperature' : IDL.Float64,
  'ammonia' : IDL.Float64,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'nitrate' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'frequencyDays' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
  'reminderType' : IDL.Text,
  'nextDue' : IDL.Int,
  'lastDone' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFishProfile' : IDL.Func([FishProfile], [], []),
  'addReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addWaterLog' : IDL.Func([WaterLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkCompatibility' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [
        IDL.Record({
          'compatible' : IDL.Bool,
          'conflicts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFishById' : IDL.Func([IDL.Nat], [IDL.Opt(FishProfile)], ['query']),
  'getReminders' : IDL.Func([IDL.Principal], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaterLogs' : IDL.Func([IDL.Principal], [IDL.Vec(WaterLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFishByName' : IDL.Func([IDL.Text], [IDL.Vec(FishProfile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FishProfile = IDL.Record({
    'id' : IDL.Nat,
    'incompatibleWith' : IDL.Vec(IDL.Text),
    'maxPH' : IDL.Float64,
    'minPH' : IDL.Float64,
    'plants' : IDL.Vec(IDL.Text),
    'minTemp' : IDL.Nat,
    'diet' : IDL.Text,
    'name' : IDL.Text,
    'compatibleWith' : IDL.Vec(IDL.Text),
    'habitat' : IDL.Text,
    'lighting' : IDL.Text,
    'scientificName' : IDL.Text,
    'minTankSize' : IDL.Nat,
    'maxTemp' : IDL.Nat,
    'filtration' : IDL.Text,
    'substrate' : IDL.Text,
    'maxTankSize' : IDL.Nat,
    'decorations' : IDL.Vec(IDL.Text),
  });
  const WaterLog = IDL.Record({
    'id' : IDL.Nat,
    'ph' : IDL.Float64,
    'temperature' : IDL.Float64,
    'ammonia' : IDL.Float64,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'nitrate' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'frequencyDays' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
    'reminderType' : IDL.Text,
    'nextDue' : IDL.Int,
    'lastDone' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFishProfile' : IDL.Func([FishProfile], [], []),
    'addReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addWaterLog' : IDL.Func([WaterLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkCompatibility' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [
          IDL.Record({
            'compatible' : IDL.Bool,
            'conflicts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFishById' : IDL.Func([IDL.Nat], [IDL.Opt(FishProfile)], ['query']),
    'getReminders' : IDL.Func([IDL.Principal], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaterLogs' : IDL.Func([IDL.Principal], [IDL.Vec(WaterLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFishByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FishProfile)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };