/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FishProfile {
  'id' : bigint,
  'incompatibleWith' : Array<string>,
  'maxPH' : number,
  'minPH' : number,
  'plants' : Array<string>,
  'minTemp' : bigint,
  'diet' : string,
  'name' : string,
  'compatibleWith' : Array<string>,
  'habitat' : string,
  'lighting' : string,
  'scientificName' : string,
  'minTankSize' : bigint,
  'maxTemp' : bigint,
  'filtration' : string,
  'substrate' : string,
  'maxTankSize' : bigint,
  'decorations' : Array<string>,
}
export interface Reminder {
  'id' : bigint,
  'frequencyDays' : bigint,
  'title' : string,
  'description' : string,
  'enabled' : boolean,
  'reminderType' : string,
  'nextDue' : bigint,
  'lastDone' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterLog {
  'id' : bigint,
  'ph' : number,
  'temperature' : number,
  'ammonia' : number,
  'notes' : string,
  'timestamp' : bigint,
  'nitrate' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFishProfile' : ActorMethod<[FishProfile], undefined>,
  'addReminder' : ActorMethod<[string, string, string, bigint], bigint>,
  'addWaterLog' : ActorMethod<[WaterLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCompatibility' : ActorMethod<
    [Array<string>],
    { 'compatible' : boolean, 'conflicts' : Array<[string, string]> }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFishById' : ActorMethod<[bigint], [] | [FishProfile]>,
  'getReminders' : ActorMethod<[Principal], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaterLogs' : ActorMethod<[Principal], Array<WaterLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFishByName' : ActorMethod<[string], Array<FishProfile>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];